import { act, render, screen } from "@testing-library/react";
import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
import { I18nProvider } from "../i18n";
import PhotoSmartClassify from "./PhotoSmartClassify";
import * as client from "../api/client";
vi.mock("../api/client", async (load) => { const actual=await load<typeof import("../api/client")>(); return {...actual,fetchPhotoFaceThumbnail:vi.fn()}; });
function renderSmart(faceId=77) { return render(<I18nProvider locale="en"><PhotoSmartClassify categories={[]} places={[]} persons={[{id:1,name:"Alice",count:1,cover_face_id:faceId}]} items={[]} onOpen={()=>undefined}/></I18nProvider>); }
describe("PhotoSmartClassify authenticated face recovery",()=>{const create=vi.fn(()=>"blob:face");const revoke=vi.fn();beforeEach(()=>{vi.useFakeTimers();vi.mocked(client.fetchPhotoFaceThumbnail).mockReset();Object.defineProperty(URL,"createObjectURL",{value:create,configurable:true});Object.defineProperty(URL,"revokeObjectURL",{value:revoke,configurable:true});});afterEach(()=>vi.useRealTimers());
it("retries the same face after 404 and recovers without remount",async()=>{vi.mocked(client.fetchPhotoFaceThumbnail).mockRejectedValueOnce(new client.PhotoFaceThumbnailPendingError()).mockResolvedValueOnce(new Blob(["jpeg"],{type:"image/jpeg"}));const view=renderSmart();await act(async()=>{await Promise.resolve();await Promise.resolve()});expect(screen.getByText("P",{selector:"div"})).toBeInTheDocument();expect(view.container.querySelector("img")).toBeNull();await act(async()=>{vi.advanceTimersByTime(5000);await Promise.resolve();await Promise.resolve()});expect(view.container.querySelector("img")?.getAttribute("src")).toBe("blob:face");expect(client.fetchPhotoFaceThumbnail).toHaveBeenNthCalledWith(1,77,expect.any(AbortSignal));expect(client.fetchPhotoFaceThumbnail).toHaveBeenNthCalledWith(2,77,expect.any(AbortSignal));expect(view.container.innerHTML).not.toContain("access_token");});
it("does not retry permanent errors",async()=>{vi.mocked(client.fetchPhotoFaceThumbnail).mockRejectedValue(new Error("403"));renderSmart();await act(async()=>{await Promise.resolve();await Promise.resolve();vi.advanceTimersByTime(600000);await Promise.resolve()});expect(client.fetchPhotoFaceThumbnail).toHaveBeenCalledTimes(1);});
it("waits for backoff after image decode error",async()=>{vi.mocked(client.fetchPhotoFaceThumbnail).mockResolvedValue(new Blob(["jpeg"]));const view=renderSmart();await act(async()=>{await Promise.resolve();await Promise.resolve()});view.container.querySelector("img")!.dispatchEvent(new Event("error"));expect(client.fetchPhotoFaceThumbnail).toHaveBeenCalledTimes(1);await act(async()=>{vi.advanceTimersByTime(4999);await Promise.resolve()});expect(client.fetchPhotoFaceThumbnail).toHaveBeenCalledTimes(1);await act(async()=>{vi.advanceTimersByTime(1);await Promise.resolve();await Promise.resolve()});expect(client.fetchPhotoFaceThumbnail).toHaveBeenCalledTimes(2);});
it("aborts and revokes object URLs when face changes",async()=>{vi.mocked(client.fetchPhotoFaceThumbnail).mockResolvedValue(new Blob(["jpeg"],{type:"image/jpeg"}));const view=renderSmart(77);await act(async()=>{await Promise.resolve();await Promise.resolve()});view.rerender(<I18nProvider locale="en"><PhotoSmartClassify categories={[]} places={[]} persons={[{id:1,name:"Alice",count:1,cover_face_id:78}]} items={[]} onOpen={()=>undefined}/></I18nProvider>);await act(async()=>{await Promise.resolve();await Promise.resolve()});expect(revoke).toHaveBeenCalledWith("blob:face");expect(client.fetchPhotoFaceThumbnail).toHaveBeenLastCalledWith(78,expect.any(AbortSignal));});});
